export const COUNTRIES = [
  { name: 'Afghanistan', code: 'af', prefix: '+93', flag: '🇦🇫' },
  { name: 'Albania', code: 'al', prefix: '+355', flag: '🇦🇱' },
  { name: 'Algeria', code: 'dz', prefix: '+213', flag: '🇩🇿' },
  { name: 'Andorra', code: 'ad', prefix: '+376', flag: '🇦🇩' },
  { name: 'Angola', code: 'ao', prefix: '+244', flag: '🇦🇴' },
  { name: 'Argentina', code: 'ar', prefix: '+54', flag: '🇦🇷' },
  { name: 'Armenia', code: 'am', prefix: '+374', flag: '🇦🇲' },
  { name: 'Australia', code: 'au', prefix: '+61', flag: '🇦🇺' },
  { name: 'Austria', code: 'at', prefix: '+43', flag: '🇦🇹' },
  { name: 'Azerbaijan', code: 'az', prefix: '+994', flag: '🇦🇿' },
  { name: 'Bahamas', code: 'bs', prefix: '+1242', flag: '🇧🇸' },
  { name: 'Bahrain', code: 'bh', prefix: '+973', flag: '🇧🇭' },
  { name: 'Bangladesh', code: 'bd', prefix: '+880', flag: '🇧🇩' },
  { name: 'Barbados', code: 'bb', prefix: '+1246', flag: '🇧🇧' },
  { name: 'Belarus', code: 'by', prefix: '+375', flag: '🇧🇾' },
  { name: 'Belgium', code: 'be', prefix: '+32', flag: '🇧🇪' },
  { name: 'Belize', code: 'bz', prefix: '+501', flag: '🇧🇿' },
  { name: 'Benin', code: 'bj', prefix: '+229', flag: '🇧🇯' },
  { name: 'Bhutan', code: 'bt', prefix: '+975', flag: '🇧🇹' },
  { name: 'Bolivia', code: 'bo', prefix: '+591', flag: '🇧🇴' },
  { name: 'Bosnia and Herzegovina', code: 'ba', prefix: '+387', flag: '🇧🇦' },
  { name: 'Botswana', code: 'bw', prefix: '+267', flag: '🇧🇼' },
  { name: 'Brazil', code: 'br', prefix: '+55', flag: '🇧🇷' },
  { name: 'Brunei', code: 'bn', prefix: '+673', flag: '🇧🇳' },
  { name: 'Bulgaria', code: 'bg', prefix: '+359', flag: '🇧🇬' },
  { name: 'Burkina Faso', code: 'bf', prefix: '+226', flag: '🇧🇫' },
  { name: 'Burundi', code: 'bi', prefix: '+257', flag: '🇧🇮' },
  { name: 'Cambodia', code: 'kh', prefix: '+855', flag: '🇰🇭' },
  { name: 'Cameroon', code: 'cm', prefix: '+237', flag: '🇨🇲' },
  { name: 'Canada', code: 'ca', prefix: '+1', flag: '🇨🇦' },
  { name: 'Cape Verde', code: 'cv', prefix: '+238', flag: '🇨🇻' },
  { name: 'Central African Republic', code: 'cf', prefix: '+236', flag: '🇨🇫' },
  { name: 'Chad', code: 'td', prefix: '+235', flag: '🇹🇩' },
  { name: 'Chile', code: 'cl', prefix: '+56', flag: '🇨🇱' },
  { name: 'China', code: 'cn', prefix: '+86', flag: '🇨🇳' },
  { name: 'Colombia', code: 'co', prefix: '+57', flag: '🇨🇴' },
  { name: 'Comoros', code: 'km', prefix: '+269', flag: '🇰🇲' },
  { name: 'Congo', code: 'cg', prefix: '+242', flag: '🇨🇬' },
  { name: 'Costa Rica', code: 'cr', prefix: '+506', flag: '🇨🇷' },
  { name: 'Croatia', code: 'hr', prefix: '+385', flag: '🇭🇷' },
  { name: 'Cuba', code: 'cu', prefix: '+53', flag: '🇨🇺' },
  { name: 'Cyprus', code: 'cy', prefix: '+357', flag: '🇨🇾' },
  { name: 'Czech Republic', code: 'cz', prefix: '+420', flag: '🇨🇿' },
  { name: 'Denmark', code: 'dk', prefix: '+45', flag: '🇩🇰' },
  { name: 'Djibouti', code: 'dj', prefix: '+253', flag: '🇩🇯' },
  { name: 'Dominica', code: 'dm', prefix: '+1767', flag: '🇩🇲' },
  { name: 'Dominican Republic', code: 'do', prefix: '+1809', flag: '🇩🇴' },
  { name: 'Ecuador', code: 'ec', prefix: '+593', flag: '🇪🇨' },
  { name: 'Egypt', code: 'eg', prefix: '+20', flag: '🇪🇬' },
  { name: 'El Salvador', code: 'sv', prefix: '+503', flag: '🇸🇻' },
  { name: 'Equatorial Guinea', code: 'gq', prefix: '+240', flag: '🇬🇶' },
  { name: 'Eritrea', code: 'er', prefix: '+291', flag: '🇪🇷' },
  { name: 'Estonia', code: 'ee', prefix: '+372', flag: '🇪🇪' },
  { name: 'Ethiopia', code: 'et', prefix: '+251', flag: '🇪🇹' },
  { name: 'Fiji', code: 'fj', prefix: '+679', flag: '🇫🇯' },
  { name: 'Finland', code: 'fi', prefix: '+358', flag: '🇫🇮' },
  { name: 'France', code: 'fr', prefix: '+33', flag: '🇫🇷' },
  { name: 'Gabon', code: 'ga', prefix: '+241', flag: '🇬🇦' },
  { name: 'Gambia', code: 'gm', prefix: '+220', flag: '🇬🇲' },
  { name: 'Georgia', code: 'ge', prefix: '+995', flag: '🇬🇪' },
  { name: 'Germany', code: 'de', prefix: '+49', flag: '🇩🇪' },
  { name: 'Ghana', code: 'gh', prefix: '+233', flag: '🇬🇭' },
  { name: 'Greece', code: 'gr', prefix: '+30', flag: '🇬🇷' },
  { name: 'Greenland', code: 'gl', prefix: '+299', flag: '🇬🇱' },
  { name: 'Grenada', code: 'gd', prefix: '+1473', flag: '🇬🇩' },
  { name: 'Guadeloupe', code: 'gp', prefix: '+590', flag: '🇬🇵' },
  { name: 'Guatemala', code: 'gt', prefix: '+502', flag: '🇬🇹' },
  { name: 'Guinea', code: 'gn', prefix: '+224', flag: '🇬🇳' },
  { name: 'Guinea-Bissau', code: 'gw', prefix: '+245', flag: '🇬🇼' },
  { name: 'Guyana', code: 'gy', prefix: '+592', flag: '🇬🇾' },
  { name: 'Haiti', code: 'ht', prefix: '+509', flag: '🇭🇹' },
  { name: 'Honduras', code: 'hn', prefix: '+504', flag: '🇭🇳' },
  { name: 'Hong Kong', code: 'hk', prefix: '+852', flag: '🇭🇰' },
  { name: 'Hungary', code: 'hu', prefix: '+36', flag: '🇭🇺' },
  { name: 'Iceland', code: 'is', prefix: '+354', flag: '🇮🇸' },
  { name: 'India', code: 'in', prefix: '+91', flag: '🇮🇳' },
  { name: 'Indonesia', code: 'id', prefix: '+62', flag: '🇮🇩' },
  { name: 'Iran', code: 'ir', prefix: '+98', flag: '🇮🇷' },
  { name: 'Iraq', code: 'iq', prefix: '+964', flag: '🇮🇶' },
  { name: 'Ireland', code: 'ie', prefix: '+353', flag: '🇮🇪' },
  { name: 'Israel', code: 'il', prefix: '+972', flag: '🇮🇱' },
  { name: 'Italy', code: 'it', prefix: '+39', flag: '🇮🇹' },
  { name: 'Jamaica', code: 'jm', prefix: '+1876', flag: '🇯🇲' },
  { name: 'Japan', code: 'jp', prefix: '+81', flag: '🇯🇵' },
  { name: 'Jordan', code: 'jo', prefix: '+962', flag: '🇯🇴' },
  { name: 'Kazakhstan', code: 'kz', prefix: '+7', flag: '🇰🇿' },
  { name: 'Kenya', code: 'ke', prefix: '+254', flag: '🇰🇪' },
  { name: 'Kiribati', code: 'ki', prefix: '+686', flag: '🇰🇮' },
  { name: 'Kuwait', code: 'kw', prefix: '+965', flag: '🇰🇼' },
  { name: 'Kyrgyzstan', code: 'kg', prefix: '+996', flag: '🇰🇬' },
  { name: 'Laos', code: 'la', prefix: '+856', flag: '🇱🇦' },
  { name: 'Latvia', code: 'lv', prefix: '+371', flag: '🇱🇻' },
  { name: 'Lebanon', code: 'lb', prefix: '+961', flag: '🇱🇧' },
  { name: 'Lesotho', code: 'ls', prefix: '+266', flag: '🇱🇸' },
  { name: 'Liberia', code: 'lr', prefix: '+231', flag: '🇱🇷' },
  { name: 'Libya', code: 'ly', prefix: '+218', flag: '🇱🇾' },
  { name: 'Liechtenstein', code: 'li', prefix: '+423', flag: '🇱🇮' },
  { name: 'Lithuania', code: 'lt', prefix: '+370', flag: '🇱🇹' },
  { name: 'Luxembourg', code: 'lu', prefix: '+352', flag: '🇱🇺' },
  { name: 'Macau', code: 'mo', prefix: '+853', flag: '🇲🇴' },
  { name: 'Macedonia', code: 'mk', prefix: '+389', flag: '🇲🇰' },
  { name: 'Madagascar', code: 'mg', prefix: '+261', flag: '🇲🇬' },
  { name: 'Malawi', code: 'mw', prefix: '+265', flag: '🇲🇼' },
  { name: 'Malaysia', code: 'my', prefix: '+60', flag: '🇲🇾' },
  { name: 'Maldives', code: 'mv', prefix: '+960', flag: '🇲🇻' },
  { name: 'Mali', code: 'ml', prefix: '+223', flag: '🇲🇱' },
  { name: 'Malta', code: 'mt', prefix: '+356', flag: '🇲🇹' },
  { name: 'Marshall Islands', code: 'mh', prefix: '+692', flag: '🇲🇭' },
  { name: 'Mauritania', code: 'mr', prefix: '+222', flag: '🇲🇷' },
  { name: 'Mauritius', code: 'mu', prefix: '+230', flag: '🇲🇺' },
  { name: 'Mexico', code: 'mx', prefix: '+52', flag: '🇲🇽' },
  { name: 'Micronesia', code: 'fm', prefix: '+691', flag: '🇫🇲' },
  { name: 'Moldova', code: 'md', prefix: '+373', flag: '🇲🇩' },
  { name: 'Monaco', code: 'mc', prefix: '+377', flag: '🇲🇨' },
  { name: 'Mongolia', code: 'mn', prefix: '+976', flag: '🇲🇳' },
  { name: 'Montenegro', code: 'me', prefix: '+382', flag: '🇲🇪' },
  { name: 'Morocco', code: 'ma', prefix: '+212', flag: '🇲🇦' },
  { name: 'Mozambique', code: 'mz', prefix: '+258', flag: '🇲🇿' },
  { name: 'Myanmar', code: 'mm', prefix: '+95', flag: '🇲🇲' },
  { name: 'Namibia', code: 'na', prefix: '+264', flag: '🇳🇦' },
  { name: 'Nauru', code: 'nr', prefix: '+674', flag: '🇳🇷' },
  { name: 'Nepal', code: 'np', prefix: '+977', flag: '🇳🇵' },
  { name: 'Netherlands', code: 'nl', prefix: '+31', flag: '🇳🇱' },
  { name: 'New Zealand', code: 'nz', prefix: '+64', flag: '🇳🇿' },
  { name: 'Nicaragua', code: 'ni', prefix: '+505', flag: '🇳🇮' },
  { name: 'Niger', code: 'ne', prefix: '+227', flag: '🇳🇪' },
  { name: 'Nigeria', code: 'ng', prefix: '+234', flag: '🇳🇬' },
  { name: 'North Korea', code: 'kp', prefix: '+850', flag: '🇰🇵' },
  { name: 'Norway', code: 'no', prefix: '+47', flag: '🇳🇴' },
  { name: 'Oman', code: 'om', prefix: '+968', flag: '🇴🇲' },
  { name: 'Pakistan', code: 'pk', prefix: '+92', flag: '🇵🇰' },
  { name: 'Palau', code: 'pw', prefix: '+680', flag: '🇵🇼' },
  { name: 'Panama', code: 'pa', prefix: '+507', flag: '🇵🇦' },
  { name: 'Papua New Guinea', code: 'pg', prefix: '+675', flag: '🇵🇬' },
  { name: 'Paraguay', code: 'py', prefix: '+595', flag: '🇵🇾' },
  { name: 'Peru', code: 'pe', prefix: '+51', flag: '🇵🇪' },
  { name: 'Philippines', code: 'ph', prefix: '+63', flag: '🇵🇭' },
  { name: 'Poland', code: 'pl', prefix: '+48', flag: '🇵🇱' },
  { name: 'Portugal', code: 'pt', prefix: '+351', flag: '🇵🇹' },
  { name: 'Qatar', code: 'qa', prefix: '+974', flag: '🇶🇦' },
  { name: 'Romania', code: 'ro', prefix: '+40', flag: '🇷🇴' },
  { name: 'Russia', code: 'ru', prefix: '+7', flag: '🇷🇺' },
  { name: 'Rwanda', code: 'rw', prefix: '+250', flag: '🇷🇼' },
  { name: 'Saint Kitts and Nevis', code: 'kn', prefix: '+1869', flag: '🇰🇳' },
  { name: 'Saint Lucia', code: 'lc', prefix: '+1758', flag: '🇱🇨' },
  { name: 'Saint Vincent', code: 'vc', prefix: '+1784', flag: '🇻🇨' },
  { name: 'Samoa', code: 'ws', prefix: '+685', flag: '🇼🇸' },
  { name: 'San Marino', code: 'sm', prefix: '+378', flag: '🇸🇲' },
  { name: 'Sao Tome and Principe', code: 'st', prefix: '+239', flag: '🇸🇹' },
  { name: 'Saudi Arabia', code: 'sa', prefix: '+966', flag: '🇸🇦' },
  { name: 'Senegal', code: 'sn', prefix: '+221', flag: '🇸🇳' },
  { name: 'Serbia', code: 'rs', prefix: '+381', flag: '🇷🇸' },
  { name: 'Seychelles', code: 'sc', prefix: '+248', flag: '🇸🇨' },
  { name: 'Sierra Leone', code: 'sl', prefix: '+232', flag: '🇸🇱' },
  { name: 'Singapore', code: 'sg', prefix: '+65', flag: '🇸🇬' },
  { name: 'Slovakia', code: 'sk', prefix: '+421', flag: '🇸🇰' },
  { name: 'Slovenia', code: 'si', prefix: '+386', flag: '🇸🇮' },
  { name: 'Solomon Islands', code: 'sb', prefix: '+677', flag: '🇸🇧' },
  { name: 'Somalia', code: 'so', prefix: '+252', flag: '🇸🇴' },
  { name: 'South Africa', code: 'za', prefix: '+27', flag: '🇿🇦' },
  { name: 'South Korea', code: 'kr', prefix: '+82', flag: '🇰🇷' },
  { name: 'South Sudan', code: 'ss', prefix: '+211', flag: '🇸🇸' },
  { name: 'Spain', code: 'es', prefix: '+34', flag: '🇪🇸' },
  { name: 'Sri Lanka', code: 'lk', prefix: '+94', flag: '🇱🇰' },
  { name: 'Sudan', code: 'sd', prefix: '+249', flag: '🇸🇩' },
  { name: 'Suriname', code: 'sr', prefix: '+597', flag: '🇸🇷' },
  { name: 'Swaziland', code: 'sz', prefix: '+268', flag: '🇸🇿' },
  { name: 'Sweden', code: 'se', prefix: '+46', flag: '🇸🇪' },
  { name: 'Switzerland', code: 'ch', prefix: '+41', flag: '🇨🇭' },
  { name: 'Syria', code: 'sy', prefix: '+963', flag: '🇸🇾' },
  { name: 'Taiwan', code: 'tw', prefix: '+886', flag: '🇹🇼' },
  { name: 'Tajikistan', code: 'tj', prefix: '+992', flag: '🇹🇯' },
  { name: 'Tanzania', code: 'tz', prefix: '+255', flag: '🇹🇿' },
  { name: 'Thailand', code: 'th', prefix: '+66', flag: '🇹🇭' },
  { name: 'Togo', code: 'tg', prefix: '+228', flag: '🇹🇬' },
  { name: 'Tonga', code: 'to', prefix: '+676', flag: '🇹🇴' },
  { name: 'Trinidad and Tobago', code: 'tt', prefix: '+1868', flag: '🇹🇹' },
  { name: 'Tunisia', code: 'tn', prefix: '+216', flag: '🇹🇳' },
  { name: 'Turkey', code: 'tr', prefix: '+90', flag: '🇹🇷' },
  { name: 'Turkmenistan', code: 'tm', prefix: '+993', flag: '🇹🇲' },
  { name: 'Tuvalu', code: 'tv', prefix: '+688', flag: '🇹🇻' },
  { name: 'Uganda', code: 'ug', prefix: '+256', flag: '🇺🇬' },
  { name: 'Ukraine', code: 'ua', prefix: '+380', flag: '🇺🇦' },
  { name: 'United Arab Emirates', code: 'ae', prefix: '+971', flag: '🇦🇪' },
  { name: 'United Kingdom', code: 'gb', prefix: '+44', flag: '🇬🇧' },
  { name: 'United States', code: 'us', prefix: '+1', flag: '🇺🇸' },
  { name: 'Uruguay', code: 'uy', prefix: '+598', flag: '🇺🇾' },
  { name: 'Uzbekistan', code: 'uz', prefix: '+998', flag: '🇺🇿' },
  { name: 'Vanuatu', code: 'vu', prefix: '+678', flag: '🇻🇺' },
  { name: 'Vatican', code: 'va', prefix: '+379', flag: '🇻🇦' },
  { name: 'Venezuela', code: 've', prefix: '+58', flag: '🇻🇪' },
  { name: 'Vietnam', code: 'vn', prefix: '+84', flag: '🇻🇳' },
  { name: 'Yemen', code: 'ye', prefix: '+967', flag: '🇾🇪' },
  { name: 'Zambia', code: 'zm', prefix: '+260', flag: '🇿🇲' },
  { name: 'Zimbabwe', code: 'zw', prefix: '+263', flag: '🇿🇼' }
];
